RegisterNetEvent('updateWeather')
AddEventHandler('updateWeather', function(weatherType)
    SetWeatherTypeNowPersist(weatherType)
    SetWeatherTypeNow(weatherType)
    SetOverrideWeather(weatherType)
    print("In-game weather updated to: " .. weatherType)
end)